substitutions:
  buzzer_pin: GPIO13
  i2s_bclk_pin: GPIO38
  i2s_din_pin: "${buzzer_pin}"
  i2s_lrclk_pin: GPIO34
  pir_pin: GPIO11
  rgb_led_pin: GPIO47
  rgb_led_type: RGB
  sen0395_io_pin: GPIO4
  uart_rx_pin: GPIO44
  uart_tx_pin: GPIO43

esp32:
  board: lolin_s3_mini
  variant: esp32s3
  flash_size: 4MB

  framework:
    type: arduino
    version: 2.0.8
    platform_version: 6.10.0

i2c:
  sda: GPIO35
  scl: GPIO36

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"

esphome:
  platformio_options:
    board_build.arduino.memory_type: qio_qspi
    board_upload.ram_size: 327680
    board_upload_maximum_size: 4193404
    board_upload_speed: 460800
    build_flags: [
      "-DBOARD_HAS_PSRAM",
      "-DARDUINO_LOLIN_S3_MINI",
      "-DARDUINO_USB_MODE=1"
    ]
