substitutions:
  buzzer_pin: GPIO1
  i2s_bclk_pin: GPIO38
  i2s_din_pin: GPIO37
  i2s_dout_pin: GPIO36
  i2s_lrclk_pin: GPIO35
  pir_pin: GPIO3
  rgb_led_pin: GPIO47
  rgb_led_type: RGB
  sen0395_io_pin: GPIO33
  uart_rx_pin: GPIO44
  uart_tx_pin: GPIO43

esp32:
  board: esp32-s3-devkitm-1
  framework:
    type: esp-idf
    version: recommended

i2c:
  sda: GPIO21
  scl: GPIO17

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"