substitutions:
  bmex80_update_interval: 30s

sensor:
  - platform: bme280
    address: 0x76
    update_interval: "${bmex80_update_interval}"
    temperature:
      name: "${name} Temperature"
    pressure:
      name: "${name} Pressure"
    humidity:
      name: "${name} Humidity"