sensor:
  - platform: bme280
    address: 0x76
    update_interval: 30s
    temperature:
      name: "${name} Temperature"
    pressure:
      name: "${name} Pressure"
    humidity:
      name: "${name} Humidity"