substitutions:
  pir_delayed_off: 1s
  pir_delayed_on: 0s

binary_sensor:
  - platform: gpio
    name: "PIR"
    id: motion_pir
    pin:
      number: "${pir_pin}"
      mode: INPUT_PULLDOWN
    device_class: motion
    filters:
      - delayed_on: "${pir_delayed_on}"
      - delayed_off: "${pir_delayed_off}"
