psram:
  mode: quad
  speed: 80MHz

i2s_audio:
  id: i2s_audiobus
  i2s_lrclk_pin: "${i2s_lrclk_pin}"  # WS
  i2s_bclk_pin: "${i2s_bclk_pin}"  # SCK

speaker:
  - platform: i2s_audio
    id: va_speaker
    i2s_dout_pin: ${i2s_dout_pin}
    dac_type: external
    channel: mono

media_player:
  - platform: speaker
    announcement_pipeline:
      speaker: va_speaker
    name: ESPHome I2S Media Player
    id: va_media_player
    on_announcement:
      - light.turn_on:
          id: led
          effect: "Fast Pulse"
    on_idle:
      - light.turn_off:
          id: led

microphone:
  - platform: i2s_audio
    id: external_microphone
    channel: left
    adc_type: external
    i2s_din_pin: "${i2s_din_pin}"  # SD
    i2s_audio_id: i2s_audiobus
    pdm: false

voice_assistant:
  id: va
  microphone: external_microphone
  media_player: va_media_player
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 60%
        effect: pulse
  on_tts_start:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 100%
        brightness: 60%
        effect: pulse
  on_end:
    - delay: 100ms
    - script.execute: reset_led
  on_error:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        brightness: 100%
        effect: none
    - delay: 1s
    - script.execute: reset_led
    - script.wait: reset_led
  on_client_connected:
    - delay: 5s
    - if:
        condition:
          lambda: return id(wake_word_engine_location).state == "On device";
        then:
          - micro_wake_word.start:
    - if:
        condition:
          lambda: return id(wake_word_engine_location).state == "In Home Assistant";
        then:
          - voice_assistant.start_continuous:
  on_client_disconnected:
    - voice_assistant.stop:
    - micro_wake_word.stop:

script:
  - id: reset_led
    then:
      - if:
          condition:
            - lambda: return id(wake_word_engine_location).state == "On device";
            - switch.is_on: listen_light
          then:
            - light.turn_on:
                id: led
                blue: 0%
                red: 0%
                green: 100%
                brightness: 60%
                effect: none
          else:
            - if:
                condition:
                  - lambda: return id(wake_word_engine_location).state == "In Home Assistant";
                  - switch.is_on: listen_light
                then:
                  - light.turn_on:
                      id: led
                      red: 0%
                      green: 100%
                      blue: 0%
                      brightness: 60%
                      effect: none
                else:
                  - light.turn_off: led

switch:
  - platform: template
    name: "VA Listen Light"
    id: listen_light
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

select:
  - id: wake_word_engine_location
    platform: template
    entity_category: config
    name: Wake word engine location
    optimistic: true
    restore_value: true
    options:
      - In Home Assistant
      - On device
      - Disable
    initial_option: Disable
    on_value:
      - if:
          condition:
            lambda: return x == "In Home Assistant";
          then:
            - micro_wake_word.stop
            - delay: 500ms
            - lambda: id(va).set_use_wake_word(true);
            - voice_assistant.start_continuous:
      - if:
          condition:
            lambda: return x == "On device";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - voice_assistant.stop
            - delay: 500ms
            - micro_wake_word.start
      - if:
          condition:
            lambda: return x == "Disable";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - voice_assistant.stop
            - micro_wake_word.stop
            - delay: 500ms
            - script.execute: reset_led

micro_wake_word:
  models:
    - model: alexa
    - model: hey_jarvis
  on_wake_word_detected:
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
