substitutions:
  name: "aiosense-c3-mini"

packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: packages
    files:
      - esphome/packages/base.yaml
      - esphome/packages/bme280.yaml
      #- esphome/packages/bme680.yaml
      #- esphome/packages/bme680_bsec.yaml
      - esphome/packages/bh1750.yaml
      - esphome/packages/pir.yaml
    refresh: 1min # optional

esphome:
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
    board_build.flash_mode: dio
#  on_boot:
#    then:
#      - light.turn_on: led
#      - delay: 3s
#      - light.turn_off: led


esp32:
  board: lolin_c3_mini
  variant: ESP32C3

# Enable Home Assistant API
api:
  encryption:
    key: "<secret>"

ota:
  password: "<secret>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dBm
  #  manual_ip:
  #    static_ip: 192.168.1.111
  #    subnet: 255.255.255.0
  #    gateway: 192.168.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"

bluetooth_proxy:

i2c:
  sda: GPIO8
  scl: GPIO10
  scan: true

uart:
  id: uart_bus
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 115200

light:
  - platform: neopixelbus
    name: "${name} LED"
    id: led
    type: GRB
    variant: WS2812X
    num_leds: 1
    pin: GPIO7
    icon: "mdi:led-outline"